services:
  subxui:
    build: .
    container_name: subxui
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/timsk.su/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/timsk.su/privkey.pem:/certs/privkey.pem:ro
    command: ["--port", "31219", "--ssl-certfile", "/certs/fullchain.pem", "--ssl-keyfile", "/certs/privkey.pem"]
